build.version=3.0

accounts.message=Welcome to JK Bank accounts related docker APIs
accounts.contactDetails.name=Krishna - Developer
accounts.contactDetails.email=krishna@jkbank.com
accounts.onCallSupport[0]=(555) 555-1234
accounts.onCallSupport[1]=(555) 523-1345
