build.version=1.0

accounts.message=Welcome to JK Bank accounts related production APIs
accounts.contactDetails.name=Aishwarya - Product Owner
accounts.contactDetails.email={cipher}5e2c40a555e1c7dabab685e09b30ef294f7bbcb570682a7b6619a5ef2d373391a1f7efa760ece40e6e6cad3479e7676d
accounts.onCallSupport[0]=(453) 392-4829
accounts.onCallSupport[1]=(236) 203-0384
