build.version=2.0

accounts.message=Welcome to JK Bank accounts related QA APIs
accounts.contactDetails.name=Smitha Ray - QA Lead
accounts.contactDetails.email=Smitha@jkjbank.com
accounts.onCallSupport[0]=(666) 265-3765
accounts.onCallSupport[1]=(666) 734-8371