build.version=3.0

cards.message=Welcome to JK Bank cards related local APIs
cards.contactDetails.name=Dragos Lech - Developer
cards.contactDetails.email=dragos@jkbank.com
cards.onCallSupport[0]=(412) 419-3494
cards.onCallSupport[1]=(915) 382-1932