build.version=3.0

loans.message=Welcome to JK Bank loans related local APIs
loans.contactDetails.name=Amaal Grega - Developer
loans.contactDetails.email=Amaal@jkbank.com
loans.onCallSupport[0]=(452) 456-2176
loans.onCallSupport[1]=(546) 764-8934